### ISSUE TITLE
Running an entire zipline algorithm using pipeline_live

### ISSUE THREAD

**Issue by ixplog** [alpacahq/pipeline-live#3]
Dear Pipeline_live Maintainers,

I am trying to execute a Zipline algorithm using data that comes from pipeline_live (that is, using factors and filters inside pipeline_live.data.iex, for example). In fact, I can create a Pipeline object and select certain stocks according to factors and filters, but I am not able to run the algorithm itself, due to a missing "pipeline_loader" or a missing "adjustment_reader" (which I don't know about).
My question is: is it possible to run an algorithm this way, using data from pipeline_live and the zipline infrastructure? If yes, what should I learn about?

Thanks,
ixplog.

**Comment by ttt733** [comment]
This is an old issue, but I believe that the intention is mostly for people to use pylivetrader with pipeline-live. Pylivetrader is zipline-based library that is set up to work with pipeline-live.
